# Generated by Django 5.1 on 2024-08-25 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_animalshelter_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalshelter',
            name='animal',
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.animalshelter'),
        ),
    ]
