# Generated by Django 5.1 on 2024-08-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_trait_animal_personality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='personality',
            field=models.ManyToManyField(null=True, to='main_app.trait'),
        ),
    ]
