# Generated by Django 5.1 on 2024-08-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_animal_personality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='personality',
            field=models.ManyToManyField(to='main_app.trait'),
        ),
    ]
