# Generated by Django 5.1 on 2024-08-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_animal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='fixed',
            field=models.CharField(choices=[('spayed', 'SPAYED'), ('neutered', 'NEUTERED')], default=None, max_length=8, null=True),
        ),
    ]
