# Generated by Django 5.1 on 2024-08-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_animallist_animals_animallist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animallist',
            name='name',
        ),
    ]
