# Generated by Django 5.1 on 2024-08-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_animallist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animallist',
            name='animals',
            field=models.ManyToManyField(null=True, to='main_app.animal'),
        ),
    ]
