# Generated by Django 5.1 on 2024-08-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_animallist_animals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animallist',
            name='animals',
            field=models.ManyToManyField(blank=True, to='main_app.animal'),
        ),
    ]
