# Generated by Django 5.1 on 2024-08-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_animallist_animals'),
    ]

    operations = [
        migrations.AddField(
            model_name='animallist',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
