# Generated by Django 5.1 on 2024-08-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_animallist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='fixed',
            field=models.CharField(choices=[('spayed', 'Spayed'), ('neutered', 'Neutered')], default=None, max_length=8, null=True),
        ),
    ]
