# Generated by Django 5.1 on 2024-08-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_animal_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='animal',
            name='description',
        ),
        migrations.AddField(
            model_name='animal',
            name='likes',
            field=models.ManyToManyField(to='main_app.interest'),
        ),
    ]
