# Generated by Django 5.1 on 2024-08-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_animal_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='likes',
            field=models.ManyToManyField(blank=True, to='main_app.interest'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='personality',
            field=models.ManyToManyField(blank=True, to='main_app.trait'),
        ),
    ]
