# Generated by Django 5.1 on 2024-08-26 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_animal_likes_alter_animal_personality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='animal_shelter',
        ),
        migrations.AddField(
            model_name='animalshelter',
            name='animals',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.animal'),
        ),
    ]
