# Generated by Django 5.1 on 2024-08-26 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_remove_animal_animal_shelter_animalshelter_animals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalshelter',
            name='animals',
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.animalshelter'),
        ),
    ]
