# Generated by Django 5.1 on 2024-08-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_remove_animalshelter_animals_animal_animal_shelter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='animal_shelter',
        ),
    ]
