# Generated by Django 5.1 on 2024-08-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_remove_animal_animal_shelter'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalshelter',
            name='animal',
            field=models.ManyToManyField(blank=True, to='main_app.animal'),
        ),
    ]
