# Generated by Django 5.1 on 2024-08-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_alter_animal_gender_alter_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='fixed',
            field=models.CharField(choices=[('spayed', 'Spayed'), ('neutered', 'Neutered'), ('not applicable', 'Not Applicable')], default=None, max_length=14, null=True),
        ),
    ]
