# Generated by Django 5.1 on 2024-08-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_alter_animal_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='fixed',
            field=models.CharField(choices=[('Spayed', 'Spayed'), ('Neutered', 'Neutered'), ('Not Applicable', 'Not Applicable')], default=None, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default=None, max_length=6, null=True),
        ),
    ]
