# Generated by Django 5.1 on 2024-08-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_alter_animal_fixed_alter_animal_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='placeholder',
            field=models.CharField(default='https://img.freepik.com/free-vector/paw-print-heart-connected_78370-3265.jpg?t=st=1724783396~exp=1724783996~hmac=aa615fe7f8e16ab94926286b46eb87e8601ab0625755b7430ab74eef35ff2826', editable=False, max_length=100),
        ),
    ]
