# Generated by Django 5.1 on 2024-08-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_alter_animal_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='placeholder',
            field=models.CharField(default='media/main_app/static/images/paw-print-heart-connected_78370-3265.avif', editable=False, max_length=100),
        ),
    ]
