# Generated by Django 5.1 on 2024-08-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_alter_animal_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='fixed',
            field=models.CharField(choices=[('Spayed', 'Spayed'), ('Neutered', 'Neutered'), ('Not Applicable', 'Not Applicable')], default=None, max_length=14),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, default='media/media/paw-print-heart-connected_78370-3265.avif', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='placeholder',
            field=models.CharField(default=' ', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], default=None, max_length=3),
        ),
    ]
