# Generated by Django 5.1 on 2024-08-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_alter_animal_fixed_alter_animal_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, default='media/paw-print-heart-connected_78370-3265.avif', null=True, upload_to='media/'),
        ),
    ]
